## create a 5x5 matrix with values ranging 3 to 7

In [2]:
import numpy as np

In [3]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a += np.arange(3,8)
a

array([[3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.]])

## create an array with shape of 4x4 and turn it into two arrays along the second axis

In [3]:
b = np.arange(16).reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
np.hsplit(b,[2,4])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

In [5]:
np.vsplit(b,[2,6])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int32)]