## generate a 1D array containing 5 random integers from 0 to 100

In [2]:
import numpy as np

In [9]:
a = np.random.randint(0,101, 5)
a

array([ 5,  0, 49, 63, 73])

## generate a 2D array with 3 rows, each row contains 5 random integers from 0 to 100

In [7]:
b = np.random.randint(0,100, size = (3,5))
b

array([[68, 73, 93, 75, 42],
       [18, 24, 52, 24, 62],
       [90, 32, 69, 10, 74]])

# Generate a 1D array of 30 evently spaced elements between 1.5 and 5.5, inlcusive

In [3]:
c = np.linspace(1.5, 5.5, 30)
c

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])